name: $(Build.BuildId)
resources:
  repositories:
  - repository: vmchooserdatabase
    type: github
    name: vmchooser/azure-vmchooser-database
    endpoint: vmchooser
trigger:
  batch: true
  branches:
    include:
    - master
stages:
- stage: Prepare
  displayName: Prepare
  jobs: 
  - job: CreateArtifact
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    - publish: $(Build.SourcesDirectory)/
      artifact: vmchooserdatabasedevelop
- stage: RetrieveProcessUpsert
  displayName: Retrieve, Process & Upsert
  jobs: 
    - deployment: RetrieveProcessUpsert
      variables:
      - group: vmchooser
      - group: vmchooserdev
      environment: 'vmchooserdev'
      strategy: 
        runOnce:
          deploy:          
            pool: 
              vmImage: 'ubuntu-latest'
            steps:
            - download: current
              artifact: vmchooserdatabasedevelop
            - bash: |
                wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
                echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
                sudo apt-get update
                sudo apt-get install -y mongodb-org-tools
              displayName: Mongodb
              workingDirectory: $(Pipeline.Workspace)/
            - bash: |
                wget -O currency.html "https://azure.microsoft.com/en-us/pricing/calculator/"
                grep -E '\global.rawCurrencyData = {(.*?)\}}' currency.html | sed 's/global.rawCurrencyData = //g' | sed 's/;//g' > currency.json
                cp currency.json ../backup/currency.json
                cp currency.json ../cloudsimple/currency.json
                cp currency.json ../compute/currency.json
                cp currency.json ../disk/currency.json
                cp currency.json ../sql/currency.json
              displayName: Currency
              workingDirectory: $(Pipeline.Workspace)/vmchooserdatabasedevelop/currency
            - bash: |
                wget -O metadata.json "https://azure.microsoft.com/api/v2/pricing/virtual-machines-base/calculator/"
                node parse.js > metadata.csv
                mongoimport --ssl --host "$(cosmosdbDatabaseName).documents.azure.com" --port 10255 -u "$(cosmosdbDatabaseName)" -p "$(cosmosdbPassword)" -d "$(cosmosdbDatabaseName)" -c "$(cosmosdbCollectionName)" --type csv --file metadata.csv --headerline --upsert --batchSize 1
              displayName: Metadata
              workingDirectory: $(Pipeline.Workspace)/vmchooserdatabasedevelop/metadata
            - bash: |
                wget -O backup.json "https://azure.microsoft.com/api/v2/pricing/backup/calculator/"
                node parse.js > backup.csv
                mongoimport --ssl --host "$(cosmosdbDatabaseName).documents.azure.com" --port 10255 -u "$(cosmosdbDatabaseName)" -p "$(cosmosdbPassword)" -d "$(cosmosdbDatabaseName)" -c "$(cosmosdbCollectionName)" --type csv --file backup.csv --headerline --upsert --batchSize 1
              displayName: Backup
              workingDirectory: $(Pipeline.Workspace)/vmchooserdatabasedevelop/backup
            - bash: |
                wget -O disk.json "https://azure.microsoft.com/api/v2/pricing/managed-disks/calculator/"
                node parse.js > disk.csv
                mongoimport --ssl --host "$(cosmosdbDatabaseName).documents.azure.com" --port 10255 -u "$(cosmosdbDatabaseName)" -p "$(cosmosdbPassword)" -d "$(cosmosdbDatabaseName)" -c "$(cosmosdbCollectionName)" --type csv --file disk.csv --headerline --upsert --batchSize 1
              displayName: Disk
              workingDirectory: $(Pipeline.Workspace)/vmchooserdatabasedevelop/disk
